Repository SoftwareMaestro-LinkLip/LinkLip-Server, pull requests merged in 2022-10, with the labels that each got.

#80 [FEAT] GYJB-205 사진 저장 API 구현
  build.gradle
  src/main/java/com/linklip/linklipserver/config/s3/AwsConfig.java
  src/main/java/com/linklip/linklipserver/constant/SuccessResponse.java
  src/main/java/com/linklip/linklipserver/controller/ContentController.java
  src/main/java/com/linklip/linklipserver/domain/content/Content.java
  src/main/java/com/linklip/linklipserver/domain/content/Image.java
  src/main/java/com/linklip/linklipserver/domain/content/Link.java
  src/main/java/com/linklip/linklipserver/domain/content/Note.java
  src/main/java/com/linklip/linklipserver/dto/content/LinkDto.java
  src/main/java/com/linklip/linklipserver/dto/content/NoteDto.java
  src/main/java/com/linklip/linklipserver/dto/content/SaveImageRequest.java
  src/main/java/com/linklip/linklipserver/repository/ContentRepository.java
  src/main/java/com/linklip/linklipserver/service/ContentService.java
  src/main/java/com/linklip/linklipserver/service/S3Upload.java
  src/main/resources/application.yml
  src/test/java/com/linklip/linklipserver/IntegrationtTest/CategoryIntegrationTest.java
  src/test/java/com/linklip/linklipserver/IntegrationtTest/ContentIntegrationTest.java
  src/test/java/com/linklip/linklipserver/TestUtils.java
  src/test/java/com/linklip/linklipserver/repository/ContentRepositoryTest.java
Labels: 🐠 준우 🐠, API, POST, Refactor 🔪, ❗️ ISSUE❗️, TEST, Feature

#82 [CHORE] GYJB-237 cors 허용 주소 추가
  src/main/java/com/linklip/linklipserver/config/CorsConfig.java
Labels: 🦋 영권 🦋

#83 [FIX] GYJB-238 토큰 재요청 시 유효하지 않은 토큰 에러 처리
  src/main/java/com/linklip/linklipserver/constant/ErrorResponse.java
  src/main/java/com/linklip/linklipserver/service/TokenService.java
Labels: 🐠 준우 🐠, API, 🛠 Fix 🛠

#84 [FEAT] GYJB-239 상태 검사 API 추가
  src/main/java/com/linklip/linklipserver/config/AuthenticationConfig.java
  src/main/java/com/linklip/linklipserver/constant/SuccessResponse.java
  src/main/java/com/linklip/linklipserver/controller/PingController.java
Labels: 🐠 준우 🐠, API, Feature

#86 [FEAT] GYJB-239 상태 검사 상태 코드 변경
  src/main/java/com/linklip/linklipserver/controller/PingController.java
Labels: 🐠 준우 🐠, API, Feature

#87 [CHORE] GYJB-237 임시로 cors origin allow all
  src/main/java/com/linklip/linklipserver/config/CorsConfig.java
Labels: 🦋 영권 🦋

#88 [FEAT] GYJB-244 OPTIONS 요청 security filter 적용 안 하도록 설정
  src/main/java/com/linklip/linklipserver/config/AuthenticationConfig.java
Labels: 🐠 준우 🐠, Feature

#91 [FIX] GYJB-244 security filter 생략 복수 응답에 대한 허용 수정
  src/main/java/com/linklip/linklipserver/config/AuthenticationConfig.java
Labels: 🐠 준우 🐠, 🛠 Fix 🛠

#92 [FEAT] GYJB-24 security filter 생략 복수 응답에 대한 허용 수정
  src/main/java/com/linklip/linklipserver/service/ContentService.java
  src/main/java/com/linklip/linklipserver/service/S3Service.java
Labels: 🐠 준우 🐠, API, DELETE

#94 [REFACTOR] GYJB-254 service 코드 읽기 쉽도록 수정
  src/main/java/com/linklip/linklipserver/service/CategoryService.java
  src/main/java/com/linklip/linklipserver/service/ContentService.java
  src/main/java/com/linklip/linklipserver/service/TokenService.java
Labels: 🐠 준우 🐠, API, Refactor 🔪
