Repository SoftwareMaestro-LinkLip/LinkLip-Server, pull requests merged in 2022-08, with the labels that each got.

#29 [GYJB-96] GitHub cache 삭제 및 application-dev.yml 파일 분리
  .gitignore
  src/main/resources/application.yml
Labels: 🦋 영권 🦋, High-Priority 🚨, Feature

#28 [GYJB-75] 링크 검색 기능 페이징 구현
  src/main/java/com/linklip/linklipserver/controller/ContentController.java
  src/main/java/com/linklip/linklipserver/dto/content/FindLinkResponse.java
  src/main/java/com/linklip/linklipserver/repository/ContentRepository.java
  src/main/java/com/linklip/linklipserver/service/ContentService.java
  src/test/java/com/linklip/linklipserver/IntegrationtTest/ContentIntegrationTest.java
  src/test/java/com/linklip/linklipserver/repository/ContentRepositoryTest.java
Labels: 🐠 준우 🐠, API, GET, TEST, Feature

#32 [GYJB-95] develop에 merged 소스코드 빌드파일 aws S3에 업로드 자동화
  .github/workflows/gradle.yml
  build.gradle
Labels: 🦋 영권 🦋, Feature, CI / CD 🐳

#38 [GYJB-103] Category domain 생성
  src/main/java/com/linklip/linklipserver/domain/Category.java
Labels: 🦋 영권 🦋, Feature

#39 [GYJB-105] 카테고리 생성 API 구현
  src/main/java/com/linklip/linklipserver/constant/SuccessResponse.java
  src/main/java/com/linklip/linklipserver/controller/CategoryController.java
  src/main/java/com/linklip/linklipserver/domain/Category.java
  src/main/java/com/linklip/linklipserver/domain/JpaBaseDomain.java
  src/main/java/com/linklip/linklipserver/dto/category/CreateCategoryRequest.java
  src/main/java/com/linklip/linklipserver/repository/CategoryRepository.java
  src/main/java/com/linklip/linklipserver/service/CategoryService.java
  src/test/java/com/linklip/linklipserver/IntegrationtTest/CategoryIntegrationTest.java
  src/test/java/com/linklip/linklipserver/repository/CategoryRepositoryTest.java
Labels: 🦋 영권 🦋, API, POST, TEST

#43 [GYJB-113] 링크 검색 API Controller -> Service로 DTO 처리 양도
  src/main/java/com/linklip/linklipserver/constant/SuccessResponse.java
  src/main/java/com/linklip/linklipserver/controller/CategoryController.java
  src/main/java/com/linklip/linklipserver/controller/ContentController.java
  src/main/java/com/linklip/linklipserver/domain/Category.java
  src/main/java/com/linklip/linklipserver/dto/category/UpdateCategoryRequest.java
  src/main/java/com/linklip/linklipserver/service/CategoryService.java
  src/main/java/com/linklip/linklipserver/service/ContentService.java
  src/test/java/com/linklip/linklipserver/IntegrationtTest/CategoryIntegrationTest.java
Labels: 🐠 준우 🐠, Refactor 🔪

#46 [GYJB-101] updateCategory 오타 수정
  src/main/java/com/linklip/linklipserver/controller/CategoryController.java
Labels: 🐠 준우 🐠, PATCH, ❗️ ISSUE❗️

#44 [GYJB-109] Content Entity 관련 리팩터링
  src/main/java/com/linklip/linklipserver/controller/ContentController.java
  src/main/java/com/linklip/linklipserver/domain/Content.java
Labels: 🦋 영권 🦋, Refactor 🔪

#45 [GYJB-118] handler500 Handling Exception 수정
  src/main/java/com/linklip/linklipserver/controller/exception/InternalErrorHandler.java
Labels: 🦋 영권 🦋

#50 Feature/gyjb 122
  src/main/java/com/linklip/linklipserver/controller/ContentController.java
  src/main/java/com/linklip/linklipserver/domain/Content.java
  src/main/java/com/linklip/linklipserver/dto/content/ContentDto.java
  src/main/java/com/linklip/linklipserver/dto/content/FindContentRequest.java
  src/main/java/com/linklip/linklipserver/repository/ContentRepository.java
  src/main/java/com/linklip/linklipserver/service/ContentService.java
  src/test/java/com/linklip/linklipserver/IntegrationtTest/ContentIntegrationTest.java
  src/test/java/com/linklip/linklipserver/repository/ContentRepositoryTest.java
Labels: 🐠 준우 🐠, API, GET, TEST

#51 [GYJB-141] Swagger가 localhost에서 작동하지 않는 이슈 해결
  src/main/resources/application.yml
Labels: 🦋 영권 🦋

#52 [GYJB-144] Swagger 문서에 Required 속성 처리
  src/main/java/com/linklip/linklipserver/dto/category/CreateCategoryRequest.java
  src/main/java/com/linklip/linklipserver/dto/category/UpdateCategoryRequest.java
  src/main/java/com/linklip/linklipserver/dto/content/SaveLinkRequest.java
Labels: 🦋 영권 🦋

#54 [GYJB-138] 특정 링크 Id에 대한 Title 및 Category 수정 API 구현
  src/main/java/com/linklip/linklipserver/constant/SuccessResponse.java
  src/main/java/com/linklip/linklipserver/controller/ContentController.java
  src/main/java/com/linklip/linklipserver/controller/exception/BadRequestHandler.java
  src/main/java/com/linklip/linklipserver/domain/Content.java
  src/main/java/com/linklip/linklipserver/dto/content/UpdateLinkRequest.java
  src/main/java/com/linklip/linklipserver/exception/InvalidIdException.java
  src/main/java/com/linklip/linklipserver/service/ContentService.java
  src/test/java/com/linklip/linklipserver/IntegrationtTest/ContentIntegrationTest.java
Labels: 🦋 영권 🦋, API, PATCH, Feature

#55 [GYJB-146] Database primary key strategy 수정
  src/main/java/com/linklip/linklipserver/domain/Category.java
  src/main/java/com/linklip/linklipserver/domain/Content.java
Labels: 🦋 영권 🦋

#56 [GYJB-137] 특정 링크 ID에 대한 데이터 반환 API 구현
  src/main/java/com/linklip/linklipserver/constant/SuccessResponse.java
  src/main/java/com/linklip/linklipserver/controller/ContentController.java
  src/main/java/com/linklip/linklipserver/controller/handler/BadRequestHandler.java
  src/main/java/com/linklip/linklipserver/controller/handler/InternalErrorHandler.java
  src/main/java/com/linklip/linklipserver/controller/handler/NotFoundHandler.java
  src/main/java/com/linklip/linklipserver/dto/content/ContentDto.java
  src/main/java/com/linklip/linklipserver/dto/content/FindContentResponse.java
  src/main/java/com/linklip/linklipserver/dto/content/FindLinkListResponse.java
  src/main/java/com/linklip/linklipserver/service/ContentService.java
  src/test/java/com/linklip/linklipserver/IntegrationtTest/ContentIntegrationTest.java
  src/test/java/com/linklip/linklipserver/repository/ContentRepositoryTest.java
Labels: 🐠 준우 🐠, API, GET, Refactor 🔪, TEST

#57 [GYJB-132] Category 삭제 API 구현
  src/main/java/com/linklip/linklipserver/constant/SuccessResponse.java
  src/main/java/com/linklip/linklipserver/controller/CategoryController.java
  src/main/java/com/linklip/linklipserver/repository/ContentRepository.java
  src/main/java/com/linklip/linklipserver/service/CategoryService.java
  src/test/java/com/linklip/linklipserver/IntegrationtTest/CategoryIntegrationTest.java
  src/test/java/com/linklip/linklipserver/IntegrationtTest/ContentIntegrationTest.java
  src/test/java/com/linklip/linklipserver/TestUtils.java
  src/test/java/com/linklip/linklipserver/repository/CategoryRepositoryTest.java
Labels: 🦋 영권 🦋, API, DELETE, ❗️ ISSUE❗️, TEST, Feature

#59 [GYJB-140] 링크 삭제 API 구현
  src/main/java/com/linklip/linklipserver/constant/SuccessResponse.java
  src/main/java/com/linklip/linklipserver/controller/ContentController.java
  src/main/java/com/linklip/linklipserver/domain/Content.java
  src/main/java/com/linklip/linklipserver/service/ContentService.java
  src/test/java/com/linklip/linklipserver/IntegrationtTest/ContentIntegrationTest.java
  src/test/java/com/linklip/linklipserver/TestUtils.java
  src/test/java/com/linklip/linklipserver/repository/CategoryRepositoryTest.java
Labels: 🐠 준우 🐠, API, DELETE, TEST

#60 [GYJB-156] allow client host to solve CORS issue
  src/main/java/com/linklip/linklipserver/LinklipserverApplication.java
Labels: 🦋 영권 🦋

#61 [GYJB-157] allow client http and https host to solve CORS issue
  src/main/java/com/linklip/linklipserver/LinklipserverApplication.java
  src/main/java/com/linklip/linklipserver/config/CorsConfig.java
Labels: 🦋 영권 🦋

#62 [GYJB-157] CorsConfig allow credential 처리
  src/main/java/com/linklip/linklipserver/config/CorsConfig.java
Labels: 🦋 영권 🦋

#63 [GYJB-158] 링크 컨텐츠 조회 경우 카테고리 id 포함하도록 수정
  src/main/java/com/linklip/linklipserver/dto/category/CategoryDto.java
  src/main/java/com/linklip/linklipserver/dto/content/ContentDto.java
  src/main/java/com/linklip/linklipserver/repository/ContentRepository.java
Labels: 🐠 준우 🐠, API, ❗️ ISSUE❗️

#64 [GYJB-162] 링크 데이터 분리
  src/main/java/com/linklip/linklipserver/constant/SuccessResponse.java
  src/main/java/com/linklip/linklipserver/controller/ContentController.java
  src/main/java/com/linklip/linklipserver/domain/Content.java
  src/main/java/com/linklip/linklipserver/domain/Link.java
  src/main/java/com/linklip/linklipserver/dto/content/FindContentResponse.java
  src/main/java/com/linklip/linklipserver/dto/content/FindLinkListResponse.java
  src/main/java/com/linklip/linklipserver/dto/content/LinkDto.java
  src/main/java/com/linklip/linklipserver/dto/content/SaveLinkRequest.java
  src/main/java/com/linklip/linklipserver/repository/ContentRepository.java
  src/main/java/com/linklip/linklipserver/service/ContentService.java
  src/test/java/com/linklip/linklipserver/IntegrationtTest/CategoryIntegrationTest.java
  src/test/java/com/linklip/linklipserver/IntegrationtTest/ContentIntegrationTest.java
  src/test/java/com/linklip/linklipserver/TestUtils.java
  src/test/java/com/linklip/linklipserver/repository/ContentRepositoryTest.java
Labels: 🐠 준우 🐠, API, Refactor 🔪, TEST
