Repository SoftwareMaestro-LinkLip/LinkLip-Server, pull requests merged in 2022-09, with the labels that each got.

#65 [CHORE] Localhost CORS 허용
  src/main/java/com/linklip/linklipserver/config/CorsConfig.java
Labels: 🦋 영권 🦋

#66 [FEAT] 링크 저장 API에 categoryId로 카테고리 설정 구현
  src/main/java/com/linklip/linklipserver/dto/content/SaveLinkRequest.java
  src/main/java/com/linklip/linklipserver/service/ContentService.java
  src/test/java/com/linklip/linklipserver/repository/ContentRepositoryTest.java
Labels: 🦋 영권 🦋, API, POST, Feature

#68 [FIX] saveNoteContent 메서드에 Transactional 어노테이션 추가
  src/main/java/com/linklip/linklipserver/service/ContentService.java
Labels: 🦋 영권 🦋, 🛠 Fix 🛠

#69 [FEAT] 메모 수정 API 구현
  src/main/java/com/linklip/linklipserver/constant/SuccessResponse.java
  src/main/java/com/linklip/linklipserver/controller/ContentController.java
  src/main/java/com/linklip/linklipserver/domain/Note.java
  src/main/java/com/linklip/linklipserver/dto/content/note/UpdateNoteRequest.java
  src/main/java/com/linklip/linklipserver/service/ContentService.java
  src/test/java/com/linklip/linklipserver/IntegrationtTest/ContentIntegrationTest.java
  src/test/java/com/linklip/linklipserver/TestUtils.java
Labels: 🐠 준우 🐠, API, PATCH, TEST, Feature

#70 [FEAT] GYJB-175 메모 조회 관련 API 구현
  src/main/java/com/linklip/linklipserver/constant/ErrorResponse.java
  src/main/java/com/linklip/linklipserver/controller/ContentController.java
  src/main/java/com/linklip/linklipserver/dto/content/ContentDto.java
  src/main/java/com/linklip/linklipserver/dto/content/LinkDto.java
  src/main/java/com/linklip/linklipserver/dto/content/NoteDto.java
  src/main/java/com/linklip/linklipserver/repository/ContentRepository.java
  src/main/java/com/linklip/linklipserver/service/CategoryService.java
  src/main/java/com/linklip/linklipserver/service/ContentService.java
  src/test/java/com/linklip/linklipserver/IntegrationtTest/CategoryIntegrationTest.java
  src/test/java/com/linklip/linklipserver/IntegrationtTest/ContentIntegrationTest.java
  src/test/java/com/linklip/linklipserver/repository/CategoryRepositoryTest.java
  src/test/java/com/linklip/linklipserver/repository/ContentRepositoryTest.java
Labels: 🦋 영권 🦋, API, GET, ❗️ ISSUE❗️, TEST, Feature

#71 [FEAT] GYJB-187 컨텐츠 검색 page size 20으로 수정
  src/main/java/com/linklip/linklipserver/controller/ContentController.java
Labels: 🐠 준우 🐠, Feature

#73 [FEAT] 개발서버 RDS 생성 및 application.yml 파일 분리
  .gitignore
  src/main/resources/application-dev.yml
  src/main/resources/application-local.yml
Labels: 🦋 영권 🦋, Feature

#74 [FIX] GYJB-200 application.yml 파일 수정
  .github/workflows/develop-deploy.yml
  .github/workflows/gradle.yml
  .gitignore
  src/main/resources/application-dev.yml
  src/main/resources/application-local.yml
  src/main/resources/application.yml
Labels: 🦋 영권 🦋, ❗️ ISSUE❗️, High-Priority 🚨, 🛠 Fix 🛠

#75 [FEAT] GYJB-193 Google OAuth 반영 및 JWT 도입
  .github/workflows/develop-deploy.yml
  .github/workflows/gradle.yml
  .gitignore
  build.gradle
  src/main/java/com/linklip/linklipserver/config/AuthenticationConfig.java
  src/main/java/com/linklip/linklipserver/config/CustomAuthenticationEntryPoint.java
  src/main/java/com/linklip/linklipserver/config/auth/PrincipalDetails.java
  src/main/java/com/linklip/linklipserver/config/filter/JwtTokenFilter.java
  src/main/java/com/linklip/linklipserver/config/oauth/OAuth2Attributes.java
  src/main/java/com/linklip/linklipserver/config/oauth/OAuth2SuccessHandler.java
  src/main/java/com/linklip/linklipserver/config/oauth/OAuth2UserService.java
  src/main/java/com/linklip/linklipserver/config/util/JwtTokenUtils.java
  src/main/java/com/linklip/linklipserver/constant/ErrorResponse.java
  src/main/java/com/linklip/linklipserver/controller/ContentController.java
  src/main/java/com/linklip/linklipserver/domain/Social.java
  src/main/java/com/linklip/linklipserver/domain/User.java
  src/main/java/com/linklip/linklipserver/repository/UserRepository.java
  src/main/java/com/linklip/linklipserver/service/UserService.java
  src/main/resources/application.yml
  src/test/java/com/linklip/linklipserver/IntegrationtTest/CategoryIntegrationTest.java
  src/test/java/com/linklip/linklipserver/IntegrationtTest/ContentIntegrationTest.java
Labels: 🐠 준우 🐠, API, TEST, Feature

#76 [FEAT] GYJB-204 Refresh Token 생성 및 토큰 재발급 구현
  src/main/java/com/linklip/linklipserver/config/AuthenticationConfig.java
  src/main/java/com/linklip/linklipserver/config/CustomAuthenticationEntryPoint.java
  src/main/java/com/linklip/linklipserver/config/auth/PrincipalDetails.java
  src/main/java/com/linklip/linklipserver/config/filter/JwtTokenFilter.java
  src/main/java/com/linklip/linklipserver/config/oauth/OAuth2SuccessHandler.java
  src/main/java/com/linklip/linklipserver/constant/ErrorResponse.java
  src/main/java/com/linklip/linklipserver/constant/SuccessResponse.java
  src/main/java/com/linklip/linklipserver/controller/ContentController.java
  src/main/java/com/linklip/linklipserver/controller/TokenController.java
  src/main/java/com/linklip/linklipserver/controller/handler/BadRequestHandler.java
  src/main/java/com/linklip/linklipserver/domain/RefreshToken.java
  src/main/java/com/linklip/linklipserver/dto/auth/ReissueTokenRequest.java
  src/main/java/com/linklip/linklipserver/exception/ExpiredTokenException.java
  src/main/java/com/linklip/linklipserver/exception/NotValidTokenException.java
  src/main/java/com/linklip/linklipserver/repository/TokenRepository.java
  src/main/java/com/linklip/linklipserver/repository/UserRepository.java
  src/main/java/com/linklip/linklipserver/service/TokenService.java
  src/main/java/com/linklip/linklipserver/service/UserService.java
  src/main/java/com/linklip/linklipserver/util/JwtTokenUtils.java
Labels: 🐠 준우 🐠, API, POST, Feature

#77 [FEAT] GYJB-204 ContextHolder 유저 정보 userId에서 user로 변경
  src/main/java/com/linklip/linklipserver/config/AuthenticationConfig.java
  src/main/java/com/linklip/linklipserver/config/filter/JwtTokenFilter.java
  src/main/java/com/linklip/linklipserver/controller/ContentController.java
  src/main/java/com/linklip/linklipserver/service/UserService.java
Labels: 🐠 준우 🐠, API, Feature

#78 [FEAT] GYJB-214 기존 API에 User 정보 추가하여 처리
  src/main/java/com/linklip/linklipserver/controller/CategoryController.java
  src/main/java/com/linklip/linklipserver/controller/ContentController.java
  src/main/java/com/linklip/linklipserver/domain/Category.java
  src/main/java/com/linklip/linklipserver/domain/Content.java
  src/main/java/com/linklip/linklipserver/domain/Link.java
  src/main/java/com/linklip/linklipserver/domain/Note.java
  src/main/java/com/linklip/linklipserver/repository/CategoryRepository.java
  src/main/java/com/linklip/linklipserver/repository/ContentRepository.java
  src/main/java/com/linklip/linklipserver/service/CategoryService.java
  src/main/java/com/linklip/linklipserver/service/ContentService.java
  src/test/java/com/linklip/linklipserver/IntegrationtTest/CategoryIntegrationTest.java
  src/test/java/com/linklip/linklipserver/IntegrationtTest/ContentIntegrationTest.java
  src/test/java/com/linklip/linklipserver/TestUtils.java
  src/test/java/com/linklip/linklipserver/repository/CategoryRepositoryTest.java
  src/test/java/com/linklip/linklipserver/repository/ContentRepositoryTest.java
Labels: 🦋 영권 🦋, API, TEST, Feature, 🛠 Fix 🛠
